version: 0.2

phases:
  install:
    commands:
      - echo Starting install phase Installing apache
      - sudo yum update -y
      - sudo yum install httpd -y

  build:
    commands:
      - echo Build started on `date`
      - echo "Ensuring /var/www/html/ exists"
      - sudo cp index.html /var/www/html/

  post_build:
    commands:
      - echo Configuring apache

artifacts:
  files:
    - /var/www/html/index.html
    - /var/www/html/appspec.yml
    - /var/www/html/scripts/*
